---
- name: Test powershell install
  hosts: all
  roles:
    - role: x_delfino.languages.pwsh
      environment:
        GITHUB_TOKEN: >-
          {{
            lookup('env', 'GITHUB_TOKEN')
            if lookup('env', 'GITHUB_TOKEN') | length > 0
          }}
