---
argument_specs:
  main:
    short_description: Main entrypoint for zig role
    options:
      zig_install_path:
        type: "path"
        required: false
        default: "$HOME/.local/zig"
        description: The path to install pyenv to.

      zig_base_url:
        type: "str"
        required: false
        default: https://ziglang.org/download
        description: The base URL to download zig from.

      zig_metadata_url:
        type: "str"
        required: false
        default: https://ziglang.org/download/index.json
        description: The URL to retrieve zig release metadata.

      zig_version:
        type: "str"
        required: false
        description: >
          The zig version to install (e.g. 0.13.0).
          'latest' will ensure that the latest release is installed.
          No value will just ensure that zig is installed.

      zig_ensure_path:
        type: "bool"
        required: false
        default: true
        description: Whether to add the zig install path to PATH.

      zig_symlink:
        type: "path"
        required: false
        description: >
          Path of a symlink to the zig binary.
          No value will skip symlink creation.
