---
galaxy_info:
  author: delfino
  role_name: zig
  description: >-
    Zig is a general-purpose programming language and toolchain for maintaining
    robust, optimal and reusable software.

  license: Apache-2.0

  min_ansible_version: '2.1'

  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Kali
      versions:
        - all

dependencies: []
