---
galaxy_info:
  author: delfino
  role_name: pwsh
  description: powershell is cool
  issue_tracker_url: test
#    PowerShell is a cross-platform task automation solution made up of a
#    command-line shell, a scripting language, and a configuration management
#    framework.

  license: Apache-2.0

  min_ansible_version: '2.1'

  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Kali
      versions:
        - all

  galaxy_tags:
    - test


dependencies: []
