---
argument_specs:
  main:
    short_description: Main entrypoint for bun role
    options:
      bun_repo:
        type: "str"
        required: false
        default: oven-sh/bun
        description: The GitHub repository to install bun from.

      bun_version:
        type: "str"
        required: false
        description: >
          The bun version to install (e.g. 1.2.3).
          'latest' will ensure that the latest release is installed.
          No value will just ensure that bun is installed.

      bun_install_path:
        type: "path"
        required: false
        default: "$HOME/.bun"
        description: The path to install bun to.

      bun_debug:
        type: "bool"
        required: false
        default: false
        description: Whether to install the debug build of bun.

      bun_ensure_path:
        type: "bool"
        required: false
        default: true
        description: Whether to add the install path to PATH.
