---
argument_specs:
  main:
    short_description: Main entrypoint for nvm role
    options:
      nvm_repo:
        type: "str"
        required: false
        default: nvm-sh/nvm
        description: The GitHub repository to install nvm from.

      nvm_version:
        type: "str"
        required: false
        description: >
          The nvm version to install (e.g. 0.40.2).
          'latest' will ensure that the latest release is installed.
          No value will just ensure that nvm is installed.

      nvm_install_path:
        type: "path"
        required: false
        default: "$HOME/.nvm"
        description: The path to install nvm to.
