---
argument_specs:
  main:
    short_description: Main entrypoint for golang role
    options:
      golang_base_url:
        type: "str"
        required: false
        default: https://go.dev/dl
        description: The base URL to download golang from.

      golang_metadata_url:
        type: "str"
        required: false
        default: https://go.dev/dl/?mode=json
        description: The URL to retrieve golang release metadata.

      golang_version:
        type: "str"
        required: false
        description: >
          The bun version to install (e.g. 1.24.2).
          'latest' will ensure that the latest release is installed.
          No value will just ensure that golang is installed.

      golang_install_path:
        type: "path"
        required: false
        default: "$HOME/.local/go"
        description: The path to install golang to.

      golang_ensure_path:
        type: "bool"
        required: false
        default: true
        description: Whether to add the golang install path to PATH.
